services:
  - type: web
    name: pskov-guide-server
    # runtime: node
    # startCommand: node init-db.js && npm start
    startCommand: npm start
    branch: main
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        value: postgresql://anya:68QlYiLJFahm5ROi5SLINEgrTUC1c1an@dpg-d252nde3jp1c73dt91mg-a.oregon-postgres.render.com/guide_yqsg
      - key: JWT_SECRET
        generateValue: true
